apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: dbconfig
stringData:
  db-url: {{ .Values.env.dburl | quote }}
  db-username: {{ .Values.env.dbusername | quote }}
  db-password: {{ .Values.env.dbpassword | quote }}
